noChunkCRC: false
noAttachmentCRC: false
enableDataCRC: false
noSummaryCRC: false
noChunking: false
noMessageIndex: false
noSummary: false
chunkSize: 62914560 # 60 MiB
compression: "None"
compressionLevel: "Default"
forceCompression: false
